// Snooker Master Constants & Boutique Catalog
// Decoupled from React components to eliminate circular dependency issues

export const TABLE_THEMES = [
  {
    id: 'championship_green',
    nameFa: 'سبز مسابقات جهانی کروسیبل',
    nameEn: 'Crucible Championship Green',
    clothColor: '#0b532c',
    cushionColor: '#073d1f',
    borderColor: '#382212',
    accentColor: '#10b981',
    price: 0,
    isFree: true,
    badge: 'استاندارد 🏆',
    desc: 'ماهوت رسمی استرابون ۱۰۰ تور جهانی شفیلد انگلستان'
  },
  {
    id: 'royal_blue',
    nameFa: 'آبی مخمل سلطنتی',
    nameEn: 'Royal Velvet Blue',
    clothColor: '#1e3a5f',
    cushionColor: '#132842',
    borderColor: '#1e293b',
    accentColor: '#38bdf8',
    price: 3500,
    isFree: false,
    badge: 'محبوب 💙',
    desc: 'پارچه پشمی با بافت متراکم و سرعت حرکت کنترل‌شده'
  },
  {
    id: 'imperial_ruby',
    nameFa: 'یاقوت سرخ امپراتوری',
    nameEn: 'Imperial Ruby Crimson',
    clothColor: '#7f1d1d',
    cushionColor: '#5c1313',
    borderColor: '#290b0b',
    accentColor: '#ef4444',
    price: 8000,
    isFree: false,
    badge: 'سلطنتی 👑',
    desc: 'میز کلاسیک بارون‌های بریتانیایی با چوب ماهون براق'
  },
  {
    id: 'cyber_neon',
    nameFa: 'سایبر نئون آبسیدین',
    nameEn: 'Cyber Neon Obsidian',
    clothColor: '#090d16',
    cushionColor: '#04070d',
    borderColor: '#020617',
    accentColor: '#06b6d4',
    price: 18000,
    isFree: false,
    badge: 'مدرن ⚡',
    desc: 'فیبر کربن ضدخش با درخشش خطوط نئونی آبی و بنفش'
  },
  {
    id: 'ancient_emerald',
    nameFa: 'زمرد کهن پارسی',
    nameEn: 'Ancient Persian Emerald',
    clothColor: '#064e3b',
    cushionColor: '#022c22',
    borderColor: '#2e1c0c',
    accentColor: '#34d399',
    price: 12000,
    isFree: false,
    badge: 'باستانی 🦅',
    desc: 'تذهیب زرین در حاشیه‌های گردویی و ماهوت اعلای ابریشمی'
  },
  {
    id: 'amethyst_royalty',
    nameFa: 'ارغوانی کریستال آمتیست',
    nameEn: 'Amethyst Royalty',
    clothColor: '#4c1d95',
    cushionColor: '#2e1065',
    borderColor: '#190a33',
    accentColor: '#c084fc',
    price: 22000,
    isFree: false,
    badge: 'افسانه‌ای 💎',
    desc: 'شاهکار بصری با جلای کریستالی امیتیست و حاشیه‌های لوکس'
  }
];

export const SNOOKER_CUES = [
  {
    id: 'ash_classic',
    nameFa: 'چوب اش سنتی (Ash Wood)',
    nameEn: 'Classic Ash Wood',
    descFa: 'چوب زبان‌گنجشک استاندارد مسابقات با توازن طبیعی و بدون انحراف.',
    descEn: 'Standard tournament grade ash wood with natural balance.',
    price: 0,
    isFree: true,
    power: 70,
    aimLength: 60,
    spinControl: 60,
    glowColor: 'rgba(217, 119, 6, 0.4)',
    accentGradient: 'from-amber-700 via-amber-600 to-amber-800',
    shaftColor: '#e2b17a',
    buttColor: '#2b1810',
    ferruleColor: '#f59e0b',
    tipColor: '#fef3c7',
    badge: 'پایه 🪵',
    icon: '🪵'
  },
  {
    id: 'maple_rookie',
    nameFa: 'افرای کانادایی (Maple Rookie)',
    nameEn: 'Canadian Maple Rookie',
    descFa: 'چوب افرای سبک و خوش‌دست با کنترل خطای بسیار کم، عالی برای شروع.',
    descEn: 'Light Canadian maple wood with low deflection, perfect for beginners.',
    price: 500,
    isFree: false,
    power: 73,
    aimLength: 64,
    spinControl: 64,
    glowColor: 'rgba(34, 197, 94, 0.45)',
    accentGradient: 'from-emerald-700 via-green-600 to-lime-800',
    shaftColor: '#f0dfc8',
    buttColor: '#1c1917',
    ferruleColor: '#86efac',
    tipColor: '#bbf7d0',
    badge: 'مبتدی 🌿',
    icon: '🌿'
  },
  {
    id: 'ebony_club',
    nameFa: 'آبنوس باشگاهی (Ebony Club)',
    nameEn: 'Ebony Club Master',
    descFa: 'چوب آبنوس آفریقایی با وزن مطلوب و کنترل ضربات نزدیک به پاکت.',
    descEn: 'Dense African ebony with excellent weight distribution for close pots.',
    price: 1200,
    isFree: false,
    power: 76,
    aimLength: 68,
    spinControl: 68,
    glowColor: 'rgba(148, 163, 184, 0.5)',
    accentGradient: 'from-slate-700 via-slate-600 to-slate-900',
    shaftColor: '#d6a570',
    buttColor: '#0f172a',
    ferruleColor: '#e2e8f0',
    tipColor: '#93c5fd',
    badge: 'اقتصادی 🎱',
    icon: '🎱'
  },
  {
    id: 'vintage_mahogany',
    nameFa: 'ماهون کلاسیک ۱۹۲۷ (Vintage Mahogany)',
    nameEn: 'Vintage Mahogany 1927',
    descFa: 'چوب ماهون کهنسال با مغزی برنجی، استواری ضربات و جذب لرزش دست.',
    descEn: 'Aged mahogany with brass balance core for vibration absorption.',
    price: 1800,
    isFree: false,
    power: 78,
    aimLength: 72,
    spinControl: 71,
    glowColor: 'rgba(180, 83, 9, 0.5)',
    accentGradient: 'from-amber-800 via-amber-700 to-amber-950',
    shaftColor: '#c28552',
    buttColor: '#3f1807',
    ferruleColor: '#f59e0b',
    tipColor: '#fde68a',
    badge: 'نوستالژی 🍂',
    icon: '🍂'
  },
  {
    id: 'persepolis_gold',
    nameFa: 'تخت جمشید زرین (Persepolis)',
    nameEn: 'Persepolis Ancient Gold',
    descFa: 'الهام‌گرفته از سرستون‌های پارسه با خط راهنمای دقیق و ضربات باثبات.',
    descEn: 'Inspired by Persepolis columns with enhanced aim line stability.',
    price: 2800,
    isFree: false,
    power: 80,
    aimLength: 76,
    spinControl: 75,
    glowColor: 'rgba(234, 179, 8, 0.5)',
    accentGradient: 'from-amber-600 via-yellow-600 to-amber-900',
    shaftColor: '#deb887',
    buttColor: '#451a03',
    ferruleColor: '#fbbf24',
    tipColor: '#fef08a',
    badge: 'باستانی 🏛️',
    icon: '🏛️'
  },
  {
    id: 'damascus_steel',
    nameFa: 'فولاد دمشقی شاه‌عباسی (Damascus Steel)',
    nameEn: 'Damascus Steel Master',
    descFa: 'تیغه فولادی نقش‌موج با مفصل تیتانیوم، انتقال صددرصدی انرژی ضربه.',
    descEn: 'Pattern-welded Damascus steel joint delivering 100% kinetic transfer.',
    price: 4200,
    isFree: false,
    power: 83,
    aimLength: 80,
    spinControl: 78,
    glowColor: 'rgba(100, 116, 139, 0.55)',
    accentGradient: 'from-slate-600 via-zinc-500 to-slate-900',
    shaftColor: '#cbd5e1',
    buttColor: '#18181b',
    ferruleColor: '#94a3b8',
    tipColor: '#f1f5f9',
    badge: 'کهن ⚔️',
    icon: '⚔️'
  },
  {
    id: 'faravahar_dragon',
    nameFa: 'فروهر شاهنشاهی (Faravahar)',
    nameEn: 'Persian Faravahar Dragon',
    descFa: 'منبت‌کاری اصیل با افزایش طول خط راهنما و دقت فوق‌العاده در کات‌ها.',
    descEn: 'Ancient carved wood boosting aiming guide length and precision.',
    price: 5500,
    isFree: false,
    power: 85,
    aimLength: 84,
    spinControl: 82,
    glowColor: 'rgba(16, 185, 129, 0.55)',
    accentGradient: 'from-emerald-700 via-teal-600 to-emerald-900',
    shaftColor: '#f3d9b1',
    buttColor: '#064e3b',
    ferruleColor: '#34d399',
    tipColor: '#6ee7b7',
    badge: 'اسطوره‌ای 🦅',
    icon: '🦅'
  },
  {
    id: 'turquoise_neyshabur',
    nameFa: 'فیروزه نیشابور (Persian Turquoise)',
    nameEn: 'Persian Turquoise Jewel',
    descFa: 'مرصع‌کاری فیروزه اصیل نیشابور با تیپ لمینت ۱۰ لایه مخصوص افه‌های چرخشی.',
    descEn: 'Inlaid with authentic Neyshabur turquoise with 10-layer spin tip.',
    price: 8500,
    isFree: false,
    power: 88,
    aimLength: 86,
    spinControl: 85,
    glowColor: 'rgba(6, 182, 212, 0.6)',
    accentGradient: 'from-cyan-600 via-teal-600 to-blue-900',
    shaftColor: '#e0f2fe',
    buttColor: '#0e7490',
    ferruleColor: '#22d3ee',
    tipColor: '#a5f3fc',
    badge: 'اصیل 🩵',
    icon: '🩵'
  },
  {
    id: 'rocket_147',
    nameFa: 'راکت اُسالیوان (The Rocket 147)',
    nameEn: 'The Rocket 147 Pro',
    descFa: 'طراحی ویژه بریک‌های ماکزیمم ۱۴۷ با سرعت شلیک بالا و فلو بی‌نقص.',
    descEn: 'Designed for 147 maximum breaks with lightning fast follow-through.',
    price: 12000,
    isFree: false,
    power: 90,
    aimLength: 88,
    spinControl: 87,
    glowColor: 'rgba(239, 68, 68, 0.6)',
    accentGradient: 'from-red-600 via-rose-700 to-red-950',
    shaftColor: '#ecd2ad',
    buttColor: '#881337',
    ferruleColor: '#fb7185',
    tipColor: '#fda4af',
    badge: 'قهرمانی 🚀',
    icon: '🚀'
  },
  {
    id: 'tiger_eye',
    nameFa: 'چشم ببر سلطنتی (Royal Tiger Eye)',
    nameEn: 'Royal Tiger Eye Master',
    descFa: 'کوارتز طلایی چشم ببر با تراکم فیبر کربن تقویت‌شده برای ضربات لانگ پات.',
    descEn: 'Golden quartz inlay with reinforced carbon matrix for supreme long potting.',
    price: 15000,
    isFree: false,
    power: 92,
    aimLength: 89,
    spinControl: 89,
    glowColor: 'rgba(245, 158, 11, 0.65)',
    accentGradient: 'from-amber-600 via-orange-600 to-amber-950',
    shaftColor: '#fed7aa',
    buttColor: '#78350f',
    ferruleColor: '#f59e0b',
    tipColor: '#ffedd5',
    badge: 'شکارچی 🐯',
    icon: '🐯'
  },
  {
    id: 'crucible_silver',
    nameFa: 'سفیر کروسیبل (Crucible Silver)',
    nameEn: 'Crucible Silver Ambassador',
    descFa: 'آلیاژ تیتانیوم و چوب افرا با بالانس هیدرولیکی مخصوص مچ‌های جهانی.',
    descEn: 'Titanium-maple composite with hydraulic balance for world championships.',
    price: 18000,
    isFree: false,
    power: 93,
    aimLength: 90,
    spinControl: 91,
    glowColor: 'rgba(203, 213, 225, 0.7)',
    accentGradient: 'from-slate-400 via-gray-500 to-slate-800',
    shaftColor: '#f1f5f9',
    buttColor: '#334155',
    ferruleColor: '#e2e8f0',
    tipColor: '#e0f2fe',
    badge: 'تخصصی 🛡️',
    icon: '🛡️'
  },
  {
    id: 'aurora_borealis',
    nameFa: 'شفق قطبی کریستال (Aurora Borealis)',
    nameEn: 'Aurora Borealis Crystal',
    descFa: 'درخشش امواج شفقی فلوئورسنت با تیپ فوق حرفه‌ای برای پیچ‌های معکوس سهمگین.',
    descEn: 'Fluorescent aurora sheen with elite laminated tip for massive screw-backs.',
    price: 24000,
    isFree: false,
    power: 94,
    aimLength: 92,
    spinControl: 94,
    glowColor: 'rgba(45, 212, 191, 0.75)',
    accentGradient: 'from-teal-400 via-emerald-500 to-indigo-700',
    shaftColor: '#ccfbf1',
    buttColor: '#134e4a',
    ferruleColor: '#2dd4bf',
    tipColor: '#5eead4',
    badge: 'درخشان 🌌',
    icon: '🌌'
  },
  {
    id: 'royal_gold',
    nameFa: 'طلای سلطنتی ۲۴ عیار (Royal Gold)',
    nameEn: 'Royal 24K Gold Master',
    descFa: 'طلاکوبی خالص با کنترل استادانه روی پیچ معکوس (Screw-Back) و کات‌های تیز.',
    descEn: 'Pure 24k gold leaf inlay with elite english and screw-back control.',
    price: 28000,
    isFree: false,
    power: 95,
    aimLength: 93,
    spinControl: 96,
    glowColor: 'rgba(245, 158, 11, 0.75)',
    accentGradient: 'from-amber-400 via-yellow-500 to-amber-600',
    shaftColor: '#fef3c7',
    buttColor: '#78350f',
    ferruleColor: '#fde047',
    tipColor: '#fef08a',
    badge: 'سلطنتی 👑',
    icon: '👑'
  },
  {
    id: 'simurgh_feather',
    nameFa: 'پر سیمرغ اساطیری (Mythical Simurgh)',
    nameEn: 'Mythical Simurgh Feather',
    descFa: 'تلفیق چوب آبنوس سلطنتی و پر طلاکاری شده سیمرغ با حداکثر واکنش روی باندها.',
    descEn: 'Mythical feather motif providing superior cushion spin rebound angles.',
    price: 35000,
    isFree: false,
    power: 96,
    aimLength: 95,
    spinControl: 97,
    glowColor: 'rgba(251, 146, 60, 0.8)',
    accentGradient: 'from-orange-500 via-amber-600 to-rose-900',
    shaftColor: '#ffedd5',
    buttColor: '#7c2d12',
    ferruleColor: '#fb923c',
    tipColor: '#fdba74',
    badge: 'اساطیری 🪶',
    icon: '🪶'
  },
  {
    id: 'cyber_plasma',
    nameFa: 'پلاسمای نئونی سایبر (Cyber Plasma)',
    nameEn: 'Cyber Neon Plasma Laser',
    descFa: 'مجهز به لیزر متمرکز و قدرت شلیک کوانتومی برای بریک‌های سنگین.',
    descEn: 'Laser assisted aiming with quantum power for massive high breaks.',
    price: 42000,
    isFree: false,
    power: 97,
    aimLength: 97,
    spinControl: 94,
    glowColor: 'rgba(56, 189, 248, 0.8)',
    accentGradient: 'from-cyan-500 via-blue-600 to-purple-700',
    shaftColor: '#38bdf8',
    buttColor: '#1e1b4b',
    ferruleColor: '#06b6d4',
    tipColor: '#67e8f9',
    badge: 'سایبرپانک ⚡',
    icon: '⚡'
  },
  {
    id: 'phoenix_blaze',
    nameFa: 'یاقوت ققنوس آتشین (Phoenix Blaze)',
    nameEn: 'Phoenix Ruby Flame Master',
    descFa: 'حکاکی شده با نگین‌های یاقوت سرخ و حداکثر پایداری در ضربات لانگ پات.',
    descEn: 'Embedded with fiery rubies providing supreme long-potting stability.',
    price: 65000,
    isFree: false,
    power: 98,
    aimLength: 97,
    spinControl: 98,
    glowColor: 'rgba(244, 63, 94, 0.85)',
    accentGradient: 'from-rose-500 via-orange-600 to-red-800',
    shaftColor: '#fed7aa',
    buttColor: '#4c0519',
    ferruleColor: '#fb7185',
    tipColor: '#f43f5e',
    badge: 'افسانه‌ای 🔥',
    icon: '🔥'
  },
  {
    id: 'quantum_infinity',
    nameFa: 'بی‌نهایت کوانتومی (Quantum Infinity)',
    nameEn: 'Quantum Infinity Void',
    descFa: 'جسم سیاه کیهانی با رگه‌های انرژی بنفش و حذف کامل خطای انحراف توپ سفید.',
    descEn: 'Deep cosmic void matter eliminating cue ball deflection entirely.',
    price: 85000,
    isFree: false,
    power: 99,
    aimLength: 99,
    spinControl: 99,
    glowColor: 'rgba(168, 85, 247, 0.85)',
    accentGradient: 'from-purple-600 via-violet-600 to-fuchsia-950',
    shaftColor: '#f3e8ff',
    buttColor: '#3b0764',
    ferruleColor: '#c084fc',
    tipColor: '#e9d5ff',
    badge: 'کوانتوم ⚛️',
    icon: '⚛️'
  },
  {
    id: 'diamond_predator',
    nameFa: 'الماس سیاه پرداتور (Black Diamond)',
    nameEn: 'Black Diamond Predator',
    descFa: 'چوب افسانه‌ای قهرمانی جهان با بالاترین سطح آمار در تمامی شاخص‌ها.',
    descEn: 'The ultimate champion predator cue with maximum stats.',
    price: 100000,
    isFree: false,
    power: 100,
    aimLength: 100,
    spinControl: 100,
    glowColor: 'rgba(236, 72, 153, 0.9)',
    accentGradient: 'from-pink-600 via-purple-700 to-indigo-900',
    shaftColor: '#fce7f3',
    buttColor: '#18181b',
    ferruleColor: '#ec4899',
    tipColor: '#f472b6',
    badge: 'شاهکار 💎',
    icon: '💎'
  }
];

export const BOT_CUES_BY_DIFFICULTY = {
  easy: 'ebony_club',
  medium: 'rocket_147',
  hard: 'diamond_predator'
};

export const BOT_PRESETS_BY_DIFFICULTY = {
  easy: {
    cueId: 'ebony_club',
    themeId: 'championship_green'
  },
  medium: {
    cueId: 'rocket_147',
    themeId: 'royal_blue'
  },
  hard: {
    cueId: 'diamond_predator',
    themeId: 'cyber_neon'
  }
};

export const DEFAULT_TABLE_THEME = TABLE_THEMES[0];
export const DEFAULT_SNOOKER_CUE = SNOOKER_CUES[0];


